### ISSUE TITLE
Is it necessary to commit?

### ISSUE THREAD

**Issue by pbrisbin** [freckle/stack-bump-lts-action#7]
I notice this action commits the changes it makes, but the prescribed usage is with `peter-evans/create-pull-request`, which can handle making the commit itself. I wonder if we'd prefer to simplify that out?

As far as I can tell, removing that and using this would result in the same outcome:

```yaml
      - id: bump
        uses: freckle/stack-bump-lts-action@main

      - name: Create PR
        if: ${{ steps.bump.outputs.newer-available }}
        uses: peter-evans/create-pull-request@v3
        with:
          branch: gh/bump-lts
          title: Bump Stackage LTS
          body: ${{ steps.bump.outputs.commit-message }}
          commit-message: ${{ steps.bump.outputs.commit-message }}
```

This will commit as `github-actions[bot]`, rather than `github.actor` (i.e. the author of the workflow file), which I think is better.
